############# English navigation ##############

# main menu
[[main]]
weight = 1
name = "Home"
url = ""
hasChildren = false

[[main]]
name = "Carpool Software"
url = "corporate-carpooling-software/"
weight = 2

[[main]]
name = "How It Works"
url = "how-it-works/"
weight = 3

[[main]]
name = "Benefits"
url = "benefits/"
weight = 4

[[main]]
name = "Pricing"
url = "pricing/"
weight = 5

[[main]]
name = "Savings Calculator"
url = "tools/savings-calculator/"
weight = 6

[[main]]
name = "Blog"
url = "blog/"
weight = 7

[[main]]
name = "Contact"
url = "contact/"
weight = 8



### footer menus

# footer_menu_3
[[footer_menu_3]]
name = "Contact"
url = "contact/"
weight = 1

[[footer_menu_3]]
name = "Privacy Policy"
url = "#!"
weight = 2

[[footer_menu_3]]
name = "Terms & Conditions"
url = "#!"
weight = 3


# footer_menu_4
[[footer_menu_4]]
name = "Carpool Software"
url = "corporate-carpooling-software/"
weight = 1

[[footer_menu_4]]
name = "How It Works"
url = "how-it-works/"
weight = 2

[[footer_menu_4]]
name = "Pricing"
url = "pricing/"
weight = 3

[[footer_menu_4]]
name = "Savings Calculator"
url = "tools/savings-calculator/"
weight = 4

[[footer_menu_4]]
name = "Blog"
url = "blog/"
weight = 5

