import type { Context } from "https://edge.netlify.com";

// Static assets don't participate in content negotiation
const STATIC_ASSET =
  /\.(css|js|png|jpg|jpeg|webp|avif|gif|svg|ico|woff|woff2|eot|ttf|otf|mp4|webm|pdf)$/i;

export default async (
  request: Request,
  context: Context,
): Promise<Response> => {
  const url = new URL(request.url);

  if (STATIC_ASSET.test(url.pathname)) {
    return context.next();
  }

  // Direct .md requests: enforce correct content-type and Vary header
  if (url.pathname.endsWith(".md")) {
    const response = await context.next();
    const headers = new Headers(response.headers);
    headers.set("Content-Type", "text/markdown; charset=utf-8");
    headers.append("Vary", "Accept");
    return new Response(response.body, {
      status: response.status,
      statusText: response.statusText,
      headers,
    });
  }

  const accept = request.headers.get("accept") ?? "";

  if (accept.includes("text/markdown")) {
    // Rewrite to Hugo's pre-rendered .md sibling (generated by outputFormats.md)
    const mdPathname = url.pathname.endsWith("/")
      ? url.pathname + "index.md"
      : url.pathname.replace(/\/?$/, "/index.md");

    const mdUrl = new URL(url.toString());
    mdUrl.pathname = mdPathname;

    const response = await context.next(new Request(mdUrl.toString()));
    const headers = new Headers(response.headers);
    headers.set("Content-Type", "text/markdown; charset=utf-8");
    headers.append("Vary", "Accept");
    return new Response(response.body, {
      status: response.status,
      statusText: response.statusText,
      headers,
    });
  }

  // Standard HTML request: add Vary so CDN caches key on the Accept header
  const response = await context.next();
  const headers = new Headers(response.headers);
  headers.append("Vary", "Accept");
  return new Response(response.body, {
    status: response.status,
    statusText: response.statusText,
    headers,
  });
};
